### ISSUE TITLE
"pip3 install murre" failed because of pyomnttok dependency

### ISSUE THREAD

**Issue by Duonghailee** [mikahama/murre#3]
Hi,

To reproduce this error:
Ubuntu Linux 5.8.0-63-generic #71~20.04.1-Ubuntu SMP / x86_64 x86_64 x86_64 GNU/Linux
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux.

When running pip3 install murre, I got this:

ERROR: Could not find a version that satisfies the requirement pyonmttok==1.10.1 (from murre) (from versions: 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.22.2, 1.23.0, 1.24.0, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4)
ERROR: No matching distribution found for pyonmttok==1.10.1

I have tried the followings:
+ upgrade pip, use pip and pip3
+ install manually pyonmttok==1.10.1 wheel.

Best regards,
Lee

**Comment by mikahama** [comment]
Try Python 3.7? Should work

**Comment by Duonghailee** [comment]
It didn't work either, [
<img width="1000" alt="Screenshot 2021-08-03 at 9 20 16" src="https://user-images.githubusercontent.com/20248988/127967512-a49f10ef-d9bb-4a99-be84-e23a30486e75.png">
](url)

I have tried the following python versions 3.2 -> 3.8

Updates:
- python3.5 seems to work best with murre, at least all dependencies are installed. However, I still got this 
"We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

spacy 2.3.7 requires tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.30.0 which is incompatible.
opennmt-tf 2.10.0 requires pyonmttok<2,>=1.18.1; platform_system == "Linux", but you'll have pyonmttok 1.10.1 which is incompatible."

**Comment by Duonghailee** [comment]
I close the issue since python3.5 works

**Comment by mikahama** [comment]
There's a new version now
